name: CI

on:
  push:
    branches: ["elamCano_p1_dev"]
  pull_request:
    branches: ["elamCano_p1_dev"]
  workflow_dispatch:

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    outputs:
      publish-path: ${{ steps.set_publish_path.outputs.path }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

        #Build
      - name: Build
        run: dotnet build --no-restore

        #Test
      - name: Run tests with coverage
        run: dotnet test ./myApp.Tests/myApp.Tests.csproj -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:CoverletOutput=./reports/coverage

      - name: Install ReportGenerator
        run: dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools

        #Coverage permission
      - name: Grant execute permission to validate_coverage.sh
        run: chmod +x ./scripts/validate_coverage.sh

      - name: Generate coverage report
        run: ./tools/reportgenerator -reports:./myApp.Tests/reports/coverage.cobertura.xml -targetdir:./myApp.Tests/reports/coveragereport -reporttypes:Html

      - name: Validate coverage
        run: ./scripts/validate_coverage.sh
        shell: bash

        #Artifact
      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./myApp.Tests/reports/coveragereport

        #Publish
      - name: Publish app
        run: dotnet publish ./myApp -c Release -o ./publish

      - name: Set publish output path
        id: set_publish_path
        run: echo "path=${{ github.workspace }}/publish" >> $GITHUB_OUTPUT

        #Deploy
      - name: Run
        run: ./publish/myApp

        #Docker build and push
      - name: Build Docker image
        run: docker build -t myconsoleapp .

      - name: Tag Docker image with v1.0.0 and latest
        run: |
          docker tag myconsoleapp ${{ secrets.DOCKER_USERNAME }}/myconsoleapp:v1.0.0
          docker tag myconsoleapp ${{ secrets.DOCKER_USERNAME }}/myconsoleapp:latest

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PAT }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/myconsoleapp:v1.0.0
          docker push ${{ secrets.DOCKER_USERNAME }}/myconsoleapp:latest
