name: CI

on:
  push:
    branches: ["elamCano_p1_dev"]
  pull_request:
    branches: ["elamCano_p1_dev"]
  workflow_dispatch:

jobs:
  build-test-publish:
    runs-on: windows-latest
    outputs:
      publish-path: ${{ steps.publish.outputs.path }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

        #build
      - name: Build
        run: dotnet build --no-restore

        #Test
      - name: Run tests with coverage
        run: dotnet test ./myApp.Tests --collect:"XPlat Code Coverage"

      - name: Install ReportGenerator
        run: dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools

      - name: Find coverage report path
        id: find_coverage
        shell: pwsh
        run: |
          $file = Get-ChildItem -Path ./myApp.Tests/TestResults -Recurse -Filter "coverage.cobertura.xml" | Select-Object -First 1
          if ($file -eq $null) {
            Write-Error "No coverage file found"
            exit 1
          }
          echo "Found: $($file.FullName)"
          echo "coverage_path=$($file.FullName)" >> $env:GITHUB_OUTPUT

      - name: Generate coverage report
        run: ./tools/reportgenerator.exe -reports:${{ steps.find_coverage.outputs.coverage_path }} -targetdir:./myApp.Tests/reports/coveragereport -reporttypes:Html

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./myApp.Tests/reports/coveragereport

        #Publish
      - name: Publish app
        id: publish
        run: dotnet publish ./myApp -c Release -o ./publish

      - name: Set publish output path
        id: set_publish_path
        run: echo "path=${{ github.workspace }}\publish" >> $env:GITHUB_ENV
        shell: powershell

  deploy:
    name: Deploy on self-hosted runner
    needs: build-test-publish
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy published app to deployment folder
        run: |
          $source = "${{ needs.build-test-publish.outputs.publish-path }}"
          $destination = "C:\Desktop\Programing\Jala Bootcamp\repos\pipelinestraining1\actions-runner"
          if (Test-Path $destination) {
            Remove-Item -Recurse -Force $destination
          }
          Copy-Item -Recurse -Force $source $destination
        shell: powershell

      - name: Restart app service (si aplica)
        run: |
          Restart-Service -Name "MyAppService"
        shell: powershell
